name: "Tmate debugging tests"
description: "Setup tmate session if the test fails"
<<<<<<< HEAD
# ...name, description and inputs as above
=======
inputs:
  use-tmate:
    description: "boolean for enabling TMATE"
    required: true
>>>>>>> fef11fa6a (ci: timeout-minutes has a known issue with composite)
runs:
  using: "composite"
  steps:
    - name: consider debugging
      shell: bash --noprofile --norc -eo pipefail -x {0}
      run: |
        # Enable tmate only in the Rook fork, where the USE_TMATE secret is set in the repo, or if the action is re-run
        if [ "$GITHUB_REPOSITORY_OWNER" = "koor-tech" ] || [ -n "${{ secrets.USE_TMATE }}" ] || [ "$GITHUB_RUN_ATTEMPT" -gt 1 ]; then
          echo USE_TMATE=1 >> $GITHUB_ENV
        fi

    - name: set up tmate session for debugging
      if: env.USE_TMATE
      uses: mxschmitt/action-tmate@v3
